version: '3.8'

services:
  django:
    container_name: django
    build:
      context: ./dcelery # Refers to the dcerly/ folder.
    command: python manage.py runserver 0.0.0.0:8000 # Run Django in the container
    volumes:
      - ./dcelery:/usr/src/app/
    ports:
      - 8001:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=0BO1203998IKLJLK12Y3U8YH81239 # Lol
      - ALLOWED_HOSTS=localhost, 127.0.0.1